# Generated by Django 2.1 on 2018-10-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trek',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='title',
        ),
        migrations.RemoveField(
            model_name='training',
            name='title',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
